default_config:
logger:
  default: error
  logs:
    custom_components.ynab: debug


#ynab:
  #api_key: API_KEY_REQUIRED
  #budget: OPTIONAL
  #name: OPTIONAL
  #categories:
  #  - "OPTIONAL"
  #  - "OPTIONAL"
